
-- DO NOT MODIFY THIS FILE !!!

function MapEditorScene:SetupUIObjects()
   self.btnSelect = self:GetButtonFromXML(3)
   self.imageSelected = self:GetStaticImageFromXML(4)
   self.groupSave = self:GetGroupFromXML(20)
   self.editSave = self:GetEditFromXML(19)
   self.btnSave = self:GetButtonFromXML(15)
   self.groupLoad = self:GetGroupFromXML(18)
   self.editLoad = self:GetEditFromXML(17)
   self.btnLoad = self:GetButtonFromXML(16)
   self.groupNew = self:GetGroupFromXML(13)
   self.editSizeX = self:GetEditFromXML(8)
   self.editSizeY = self:GetEditFromXML(9)
   self.textSizeX = self:GetTextFromXML(10)
   self.textSizeY = self:GetTextFromXML(11)
   self.btnNew = self:GetButtonFromXML(12)
   self.groupState = self:GetGroupFromXML(14)
   self.textCurrentImage = self:GetTextFromXML(5)
   self.textCurrentIndex = self:GetTextFromXML(6)
   self.textCurrentType = self:GetTextFromXML(7)
   self.btnPrint = self:GetButtonFromXML(21)

   self.groupSave:AddChild(self.editSave)
   self.groupSave:AddChild(self.btnSave)
   self.groupLoad:AddChild(self.editLoad)
   self.groupLoad:AddChild(self.btnLoad)
   self.groupNew:AddChild(self.editSizeX)
   self.groupNew:AddChild(self.editSizeY)
   self.groupNew:AddChild(self.textSizeX)
   self.groupNew:AddChild(self.textSizeY)
   self.groupNew:AddChild(self.btnNew)
   self.groupState:AddChild(self.textCurrentImage)
   self.groupState:AddChild(self.textCurrentIndex)
   self.groupState:AddChild(self.textCurrentType)
end
