
-- DO NOT MODIFY THIS FILE !!!

function iDoLobby_PopupScene:SetupUIObjects()
   self.grpCreateRoom = self:GetGroupFromXML(340)
   self.imgBg = self:GetImageFromXML(341)
   self.edtRoomTitle = self:GetEditFromXML(342)
   self.chkRoomTitleCombo = self:GetCheckBoxFromXML(343)
   self.radPasswordOption1 = self:GetRadioButtonFromXML(344)
   self.radPasswordOption2 = self:GetRadioButtonFromXML(345)
   self.edtPassword = self:GetEditFromXML(346)
   self.radInviteOption1 = self:GetRadioButtonFromXML(347)
   self.radInviteOption2 = self:GetRadioButtonFromXML(348)
   self.radInviteOption3 = self:GetRadioButtonFromXML(349)
   self.btnOK = self:GetButtonFromXML(350)
   self.btnCancel = self:GetButtonFromXML(351)
   self.btnClose = self:GetButtonFromXML(352)
   self.imgRoomTitleComboBg = self:GetImageFromXML(353)
   self.imgRoomTitleComboBgTop = self:GetStaticImageFromXML(354)
   self.imgRoomTitleComboBgBottom = self:GetStaticImageFromXML(355)
   self.txtSelectCount = self:GetTextFromXML(356)
   self.txtSelectString = self:GetTextFromXML(357)
   self.btnModify = self:GetButtonFromXML(358)
   self.grpPassword = self:GetGroupFromXML(359)
   self.passwordBg = self:GetImageFromXML(360)
   self.editPassword = self:GetEditFromXML(361)
   self.btnPasswordOK = self:GetButtonFromXML(362)
   self.btnPasswordCancel = self:GetButtonFromXML(363)
   self.grpInvite = self:GetGroupFromXML(364)
   self.imgChosens = self:GetImageFromXML(59128)
   self.imgCandidates = self:GetImageFromXML(59127)
   self.inviteBg = self:GetImageFromXML(57077)
   self.grpCandidates = self:GetGroupFromXML(59129)
   self.grpCandidatesScr = self:GetGroupFromXML(58136)
   self.btnInviteClose = self:GetButtonFromXML(59130)
   self.btnInviteOK = self:GetButtonFromXML(59131)
   self.btnInviteCancel = self:GetButtonFromXML(59132)
   self.btnInviteFind = self:GetButtonFromXML(59133)
   self.scrCandidates = self:GetVertScrollBarFromXML(59134)
   self.edtPlayerSearch = self:GetEditFromXML(59135)
   self.scrChosens = self:GetVertScrollBarFromXML(59136)
   self.grpChosens = self:GetGroupFromXML(59137)
   self.grpChosensScr = self:GetGroupFromXML(58282)
   self.grpInviteAccept = self:GetGroupFromXML(59138)
   self.inviteAcceptBg = self:GetImageFromXML(59139)
   self.btnInviteAccept = self:GetButtonFromXML(59140)
   self.btnInviteReject = self:GetButtonFromXML(59141)
   self.txtInviter = self:GetTextFromXML(59142)
   self.txtRemainTime = self:GetTextFromXML(59143)
   self.imgLoadingBar = self:GetStaticImageFromXML(59144)
   self.grpAccuse = self:GetGroupFromXML(59145)
   self.accuseBg = self:GetImageFromXML(59146)
   self.btnAccuseExit = self:GetButtonFromXML(59147)
   self.txtAccuseNick = self:GetTextFromXML(59148)
   self.radioAccuse1 = self:GetRadioButtonFromXML(59149)
   self.radioAccuse2 = self:GetRadioButtonFromXML(59150)
   self.radioAccuse3 = self:GetRadioButtonFromXML(59151)
   self.radioAccuse4 = self:GetRadioButtonFromXML(59152)
   self.radioAccuse5 = self:GetRadioButtonFromXML(59153)
   self.radioAccuse6 = self:GetRadioButtonFromXML(59154)
   self.radioAccuse7 = self:GetRadioButtonFromXML(59155)
   self.editAccuseReport = self:GetEditFromXML(59156)
   self.btnAccuseOK = self:GetButtonFromXML(59157)
   self.btnAccuseCancel = self:GetButtonFromXML(59158)
   self.grpPlayerList = self:GetGroupFromXML(59159)
   self.scrChatter = self:GetVertScrollBarFromXML(59160)
   self.grpAccuseResult = self:GetGroupFromXML(59161)
   self.accuseResultBg = self:GetImageFromXML(59162)
   self.btnAccuseResultOK = self:GetButtonFromXML(59163)
   self.btnAccuseResultExit = self:GetButtonFromXML(59164)
   self.imgAccuseUrlLink = self:GetImageFromXML(59165)
   self.imgAccuseUrlLink2 = self:GetImageFromXML(59166)
   self.grpRanking = self:GetGroupFromXML(59167)
   self.rankingBg = self:GetImageFromXML(59168)
   self.imgDayRanking = self:GetImageFromXML(59169)
   self.imgTotalRanking = self:GetImageFromXML(59170)
   self.cbRankingList = self:GetComboBoxFromXML(59171)
   self.btnMyRanking = self:GetButtonFromXML(59172)
   self.btnPrevPage = self:GetButtonFromXML(59173)
   self.btnNextPage = self:GetButtonFromXML(59174)
   self.txtRankingRange = self:GetTextFromXML(59175)
   self.btnRankingExit = self:GetButtonFromXML(59176)
   self.btnRankingClose = self:GetButtonFromXML(59177)
   self.txtRankingMessage = self:GetTextFromXML(59178)
   self.grpRankingList = self:GetGroupFromXML(59179)
   self.grpMessageBox = self:GetGroupFromXML(59180)
   self.imgModal = self:GetImageFromXML(59181)
   self.messageBoxBg = self:GetImageFromXML(59182)
   self.messageBoxBg4 = self:GetImageFromXML(59183)
   self.txtMessage1 = self:GetTextFromXML(59184)
   self.txtMessage2 = self:GetTextFromXML(59185)
   self.txtMessage3 = self:GetTextFromXML(59186)
   self.txtMessage4 = self:GetTextFromXML(59187)
   self.btnMessageBoxExit = self:GetButtonFromXML(59188)

   self.grpCreateRoom:AddChild(self.imgBg)
   self.grpCreateRoom:AddChild(self.edtRoomTitle)
   self.grpCreateRoom:AddChild(self.chkRoomTitleCombo)
   self.grpCreateRoom:AddChild(self.radPasswordOption1)
   self.grpCreateRoom:AddChild(self.radPasswordOption2)
   self.grpCreateRoom:AddChild(self.edtPassword)
   self.grpCreateRoom:AddChild(self.radInviteOption1)
   self.grpCreateRoom:AddChild(self.radInviteOption2)
   self.grpCreateRoom:AddChild(self.radInviteOption3)
   self.grpCreateRoom:AddChild(self.btnOK)
   self.grpCreateRoom:AddChild(self.btnCancel)
   self.grpCreateRoom:AddChild(self.btnClose)
   self.grpCreateRoom:AddChild(self.imgRoomTitleComboBg)
   self.grpCreateRoom:AddChild(self.imgRoomTitleComboBgTop)
   self.grpCreateRoom:AddChild(self.imgRoomTitleComboBgBottom)
   self.grpCreateRoom:AddChild(self.txtSelectCount)
   self.grpCreateRoom:AddChild(self.txtSelectString)
   self.grpCreateRoom:AddChild(self.btnModify)
   self.grpPassword:AddChild(self.passwordBg)
   self.grpPassword:AddChild(self.editPassword)
   self.grpPassword:AddChild(self.btnPasswordOK)
   self.grpPassword:AddChild(self.btnPasswordCancel)
   self.grpInvite:AddChild(self.imgChosens)
   self.grpInvite:AddChild(self.imgCandidates)
   self.grpInvite:AddChild(self.inviteBg)
   self.grpInvite:AddChild(self.grpCandidates)
   self.grpInvite:AddChild(self.grpCandidatesScr)
   self.grpInvite:AddChild(self.btnInviteClose)
   self.grpInvite:AddChild(self.btnInviteOK)
   self.grpInvite:AddChild(self.btnInviteCancel)
   self.grpInvite:AddChild(self.btnInviteFind)
   self.grpInvite:AddChild(self.scrCandidates)
   self.grpInvite:AddChild(self.edtPlayerSearch)
   self.grpInvite:AddChild(self.scrChosens)
   self.grpInvite:AddChild(self.grpChosens)
   self.grpInvite:AddChild(self.grpChosensScr)
   self.grpInviteAccept:AddChild(self.inviteAcceptBg)
   self.grpInviteAccept:AddChild(self.btnInviteAccept)
   self.grpInviteAccept:AddChild(self.btnInviteReject)
   self.grpInviteAccept:AddChild(self.txtInviter)
   self.grpInviteAccept:AddChild(self.txtRemainTime)
   self.grpInviteAccept:AddChild(self.imgLoadingBar)
   self.grpAccuse:AddChild(self.accuseBg)
   self.grpAccuse:AddChild(self.btnAccuseExit)
   self.grpAccuse:AddChild(self.txtAccuseNick)
   self.grpAccuse:AddChild(self.radioAccuse1)
   self.grpAccuse:AddChild(self.radioAccuse2)
   self.grpAccuse:AddChild(self.radioAccuse3)
   self.grpAccuse:AddChild(self.radioAccuse4)
   self.grpAccuse:AddChild(self.radioAccuse5)
   self.grpAccuse:AddChild(self.radioAccuse6)
   self.grpAccuse:AddChild(self.radioAccuse7)
   self.grpAccuse:AddChild(self.editAccuseReport)
   self.grpAccuse:AddChild(self.btnAccuseOK)
   self.grpAccuse:AddChild(self.btnAccuseCancel)
   self.grpAccuse:AddChild(self.grpPlayerList)
   self.grpAccuse:AddChild(self.scrChatter)
   self.grpAccuseResult:AddChild(self.accuseResultBg)
   self.grpAccuseResult:AddChild(self.btnAccuseResultOK)
   self.grpAccuseResult:AddChild(self.btnAccuseResultExit)
   self.grpAccuseResult:AddChild(self.imgAccuseUrlLink)
   self.grpAccuseResult:AddChild(self.imgAccuseUrlLink2)
   self.grpRanking:AddChild(self.rankingBg)
   self.grpRanking:AddChild(self.imgDayRanking)
   self.grpRanking:AddChild(self.imgTotalRanking)
   self.grpRanking:AddChild(self.cbRankingList)
   self.grpRanking:AddChild(self.btnMyRanking)
   self.grpRanking:AddChild(self.btnPrevPage)
   self.grpRanking:AddChild(self.btnNextPage)
   self.grpRanking:AddChild(self.txtRankingRange)
   self.grpRanking:AddChild(self.btnRankingExit)
   self.grpRanking:AddChild(self.btnRankingClose)
   self.grpRanking:AddChild(self.txtRankingMessage)
   self.grpRanking:AddChild(self.grpRankingList)
   self.grpMessageBox:AddChild(self.imgModal)
   self.grpMessageBox:AddChild(self.messageBoxBg)
   self.grpMessageBox:AddChild(self.messageBoxBg4)
   self.grpMessageBox:AddChild(self.txtMessage1)
   self.grpMessageBox:AddChild(self.txtMessage2)
   self.grpMessageBox:AddChild(self.txtMessage3)
   self.grpMessageBox:AddChild(self.txtMessage4)
   self.grpMessageBox:AddChild(self.btnMessageBoxExit)
end
