
-- DO NOT MODIFY THIS FILE !!!

function iDoLobby_LobbyMainScene:SetupUIObjects()
   self.grpLobby = self:GetGroupFromXML(313)
   self.txtGameTitle = self:GetTextFromXML(314)
   self.txtRoomCount = self:GetTextFromXML(315)
   self.imgSep = self:GetStaticImageFromXML(316)
   self.chkShowAvailRoom = self:GetCheckBoxFromXML(317)
   self.chkSortRoom = self:GetCheckBoxFromXML(318)
   self.btnDirectStart = self:GetButtonFromXML(319)
   self.btnCreateRoom = self:GetButtonFromXML(320)
   self.btnSingleGame = self:GetButtonFromXML(321)
   self.btnRanking = self:GetButtonFromXML(322)
   self.txtPlayer = self:GetTextFromXML(323)
   self.playerListWnd = self:GetPlayerListWndFromXML(324)
   self.btnChannelExit = self:GetButtonFromXML(325)
   self.roomListWnd = self:GetRoomListWndFromXML(326)
   self.chkChattingTitle = self:GetCheckBoxFromXML(327)
   self.txtChattingChannel = self:GetTextFromXML(328)
   self.chatWindow = self:GetChatWndFromXML(329)
   self.cmbLobbyList = self:GetComboBoxFromXML(330)
   self.txtLobbyName = self:GetTextFromXML(331)
   self.grpPopup = self:GetGroupFromXML(332)

   self.grpLobby:AddChild(self.txtGameTitle)
   self.grpLobby:AddChild(self.txtRoomCount)
   self.grpLobby:AddChild(self.imgSep)
   self.grpLobby:AddChild(self.chkShowAvailRoom)
   self.grpLobby:AddChild(self.chkSortRoom)
   self.grpLobby:AddChild(self.btnDirectStart)
   self.grpLobby:AddChild(self.btnCreateRoom)
   self.grpLobby:AddChild(self.btnSingleGame)
   self.grpLobby:AddChild(self.btnRanking)
   self.grpLobby:AddChild(self.txtPlayer)
   self.grpLobby:AddChild(self.playerListWnd)
   self.grpLobby:AddChild(self.btnChannelExit)
   self.grpLobby:AddChild(self.roomListWnd)
   self.grpLobby:AddChild(self.chkChattingTitle)
   self.grpLobby:AddChild(self.txtChattingChannel)
   self.grpLobby:AddChild(self.chatWindow)
   self.grpLobby:AddChild(self.cmbLobbyList)
   self.grpLobby:AddChild(self.txtLobbyName)
end
