
-- DO NOT MODIFY THIS FILE !!!

function Scene_WaitingRoom:SetupUIObjects()
   self.btnExit = self:GetButtonFromXML(200)
   self.btnReady = self:GetButtonFromXML(201)
   self.playerSlotBg = self:GetStaticImageFromXML(202)
   self.imageReady = self:GetStaticImageFromXML(203)
   self.textPlayer = self:GetTextFromXML(204)
   self.imageHost = self:GetStaticImageFromXML(205)
   self.groupCar = self:GetGroupFromXML(206)
   self.groupCar1 = self:GetGroupFromXML(91)
   self.imageCar11 = self:GetStaticImageFromXML(45)
   self.imageCar12 = self:GetStaticImageFromXML(46)
   self.imageCar13 = self:GetStaticImageFromXML(47)
   self.imageCar14 = self:GetStaticImageFromXML(48)
   self.imageCar15 = self:GetStaticImageFromXML(51)
   self.imageCar16 = self:GetStaticImageFromXML(52)
   self.groupCar2 = self:GetGroupFromXML(92)
   self.imageCar21 = self:GetStaticImageFromXML(55)
   self.imageCar22 = self:GetStaticImageFromXML(56)
   self.imageCar23 = self:GetStaticImageFromXML(57)
   self.imageCar24 = self:GetStaticImageFromXML(58)
   self.imageCar25 = self:GetStaticImageFromXML(59)
   self.imageCar26 = self:GetStaticImageFromXML(60)
   self.groupCar3 = self:GetGroupFromXML(93)
   self.imageCar31 = self:GetStaticImageFromXML(67)
   self.imageCar32 = self:GetStaticImageFromXML(68)
   self.imageCar33 = self:GetStaticImageFromXML(69)
   self.imageCar34 = self:GetStaticImageFromXML(70)
   self.imageCar35 = self:GetStaticImageFromXML(71)
   self.imageCar36 = self:GetStaticImageFromXML(72)
   self.groupCar4 = self:GetGroupFromXML(94)
   self.imageCar41 = self:GetStaticImageFromXML(75)
   self.imageCar42 = self:GetStaticImageFromXML(76)
   self.imageCar43 = self:GetStaticImageFromXML(77)
   self.imageCar44 = self:GetStaticImageFromXML(78)
   self.imageCar45 = self:GetStaticImageFromXML(79)
   self.imageCar46 = self:GetStaticImageFromXML(80)
   self.groupCar5 = self:GetGroupFromXML(95)
   self.imageCar51 = self:GetStaticImageFromXML(83)
   self.imageCar52 = self:GetStaticImageFromXML(84)
   self.imageCar53 = self:GetStaticImageFromXML(85)
   self.imageCar54 = self:GetStaticImageFromXML(86)
   self.imageCar55 = self:GetStaticImageFromXML(87)
   self.imageCar56 = self:GetStaticImageFromXML(88)
   self.groupBigCar = self:GetGroupFromXML(207)
   self.imageBigChar1 = self:GetStaticImageFromXML(105)
   self.imageBigChar2 = self:GetStaticImageFromXML(106)
   self.imageBigChar3 = self:GetStaticImageFromXML(107)
   self.imageBigChar4 = self:GetStaticImageFromXML(108)
   self.imageBigChar5 = self:GetStaticImageFromXML(109)
   self.groupSmallChar = self:GetGroupFromXML(208)
   self.imageSmallChar1 = self:GetImageFromXML(112)
   self.imageSmallChar2 = self:GetImageFromXML(113)
   self.imageSmallChar3 = self:GetImageFromXML(115)
   self.imageSmallChar4 = self:GetImageFromXML(116)
   self.imageSmallChar5 = self:GetImageFromXML(117)
   self.textlistChat = self:GetTextListFromXML(209)
   self.vscrollChat = self:GetVertScrollBarFromXML(121)
   self.editChat = self:GetEditFromXML(210)
   self.groupMapInfo = self:GetGroupFromXML(304)
   self.imageMapDifficulty = self:GetImageFromXML(301)
   self.textMapName = self:GetTextFromXML(302)
   self.imageMap = self:GetStaticImageFromXML(303)
   self.btnPrevMap = self:GetButtonFromXML(216)
   self.btnNextMap = self:GetButtonFromXML(217)

   self.groupCar:AddChild(self.groupCar1)
   self.groupCar1:AddChild(self.imageCar11)
   self.groupCar1:AddChild(self.imageCar12)
   self.groupCar1:AddChild(self.imageCar13)
   self.groupCar1:AddChild(self.imageCar14)
   self.groupCar1:AddChild(self.imageCar15)
   self.groupCar1:AddChild(self.imageCar16)
   self.groupCar:AddChild(self.groupCar2)
   self.groupCar2:AddChild(self.imageCar21)
   self.groupCar2:AddChild(self.imageCar22)
   self.groupCar2:AddChild(self.imageCar23)
   self.groupCar2:AddChild(self.imageCar24)
   self.groupCar2:AddChild(self.imageCar25)
   self.groupCar2:AddChild(self.imageCar26)
   self.groupCar:AddChild(self.groupCar3)
   self.groupCar3:AddChild(self.imageCar31)
   self.groupCar3:AddChild(self.imageCar32)
   self.groupCar3:AddChild(self.imageCar33)
   self.groupCar3:AddChild(self.imageCar34)
   self.groupCar3:AddChild(self.imageCar35)
   self.groupCar3:AddChild(self.imageCar36)
   self.groupCar:AddChild(self.groupCar4)
   self.groupCar4:AddChild(self.imageCar41)
   self.groupCar4:AddChild(self.imageCar42)
   self.groupCar4:AddChild(self.imageCar43)
   self.groupCar4:AddChild(self.imageCar44)
   self.groupCar4:AddChild(self.imageCar45)
   self.groupCar4:AddChild(self.imageCar46)
   self.groupCar:AddChild(self.groupCar5)
   self.groupCar5:AddChild(self.imageCar51)
   self.groupCar5:AddChild(self.imageCar52)
   self.groupCar5:AddChild(self.imageCar53)
   self.groupCar5:AddChild(self.imageCar54)
   self.groupCar5:AddChild(self.imageCar55)
   self.groupCar5:AddChild(self.imageCar56)
   self.groupBigCar:AddChild(self.imageBigChar1)
   self.groupBigCar:AddChild(self.imageBigChar2)
   self.groupBigCar:AddChild(self.imageBigChar3)
   self.groupBigCar:AddChild(self.imageBigChar4)
   self.groupBigCar:AddChild(self.imageBigChar5)
   self.groupSmallChar:AddChild(self.imageSmallChar1)
   self.groupSmallChar:AddChild(self.imageSmallChar2)
   self.groupSmallChar:AddChild(self.imageSmallChar3)
   self.groupSmallChar:AddChild(self.imageSmallChar4)
   self.groupSmallChar:AddChild(self.imageSmallChar5)
   self.groupMapInfo:AddChild(self.imageMapDifficulty)
   self.groupMapInfo:AddChild(self.textMapName)
   self.groupMapInfo:AddChild(self.imageMap)
end
